#!/usr/bin/env bash
# One-time setup for the ace-step-ui frontend (github.com/fspecii/ace-step-ui).
# Run ./setup.sh first — this assumes ACE-Step itself is already installed.
set -euo pipefail

VOL="${VOL:-/workspace}"
UI_DIR="$VOL/ace-step-ui"
NODE_DIR="$VOL/node"
# v24 LTS: @vitejs/plugin-react needs ^20.19 || >=22.12, and 20.18 missed it.
NODE_VERSION="${NODE_VERSION:-v24.18.0}"

if [[ ! -d "$VOL/ACE-Step-1.5" ]]; then
    echo "ERROR: $VOL/ACE-Step-1.5 not found. Run ./setup.sh first." >&2
    exit 1
fi

# Node goes on the volume so new pods reuse it instead of re-downloading.
# Runs node rather than testing for an executable file, so a half-extracted
# tarball is replaced instead of being mistaken for a working install. Also
# reinstalls when the version differs from NODE_VERSION.
installed_node="$("$NODE_DIR/bin/node" --version 2>/dev/null || true)"
node_changed=0
if [[ "$installed_node" != "$NODE_VERSION" ]]; then
    node_changed=1
    echo "[setup-ui] installing Node $NODE_VERSION to $NODE_DIR (found: ${installed_node:-none})..."
    rm -rf "$NODE_DIR"
    # .tar.gz rather than .tar.xz: gzip is always present, xz-utils may not be.
    tarball="node-${NODE_VERSION}-linux-x64.tar.gz"
    curl -fsSL "https://nodejs.org/dist/${NODE_VERSION}/${tarball}" -o "/tmp/$tarball"
    mkdir -p "$NODE_DIR"
    # --no-same-owner: the tarball records uid/gid 1001, and restoring that on a
    # network volume fails with "Cannot change ownership ... Operation not
    # permitted". Everything here runs as root anyway.
    tar -xzf "/tmp/$tarball" -C "$NODE_DIR" --strip-components=1 --no-same-owner
    rm -f "/tmp/$tarball"
fi
export PATH="$NODE_DIR/bin:$PATH"

# The volume does not reliably preserve the executable bit from the tarball —
# the node binary survives but npm/npx come through non-executable, failing with
# "Permission denied". chmod follows the bin/ symlinks to their real targets.
chmod +x "$NODE_DIR/bin/"* 2>/dev/null || true

# Invoke npm through node rather than its shebang, so setup does not depend on
# that exec bit at all.
NPM=("$NODE_DIR/bin/node" "$NODE_DIR/lib/node_modules/npm/bin/npm-cli.js")
echo "[setup-ui] node $(node --version), npm $("${NPM[@]}" --version)"

# ffmpeg lives on the container disk, so it needs reinstalling on each new pod.
if ! command -v ffmpeg &>/dev/null; then
    echo "[setup-ui] installing ffmpeg..."
    apt-get update -qq && apt-get install -y -qq ffmpeg
fi

if [[ -d "$UI_DIR/.git" ]]; then
    echo "[setup-ui] updating existing checkout..."
    git -C "$UI_DIR" pull --ff-only
else
    echo "[setup-ui] cloning ace-step-ui..."
    git clone https://github.com/fspecii/ace-step-ui.git "$UI_DIR"
fi

# A Node major bump changes the native ABI, so better-sqlite3 has to be rebuilt
# against the new one rather than reused.
if [[ "$node_changed" -eq 1 || "${FORCE_REINSTALL:-0}" == "1" ]]; then
    rm -rf "$UI_DIR/node_modules" "$UI_DIR/server/node_modules"
fi

echo "[setup-ui] installing npm dependencies (a few minutes)..."
cd "$UI_DIR" && "${NPM[@]}" install --no-fund --no-audit
cd "$UI_DIR/server" && "${NPM[@]}" install --no-fund --no-audit

# npm writes node_modules/.bin symlinks with the same exec-bit problem, and
# start-ui.sh runs vite and tsx from there.
chmod +x "$UI_DIR/node_modules/.bin/"* "$UI_DIR/server/node_modules/.bin/"* 2>/dev/null || true

# A separate Vite config rather than an edit to vite.config.ts, so `git pull`
# in the UI checkout never conflicts. It imports the upstream config and layers
# on the two things RunPod needs: host allowlisting and auth.
cat > "$UI_DIR/vite.config.runpod.ts" <<'VITECONFIG'
// Generated by runpods-aimusic/setup-ui.sh — do not edit by hand.
// Wraps the upstream vite.config.ts instead of modifying it.
import { defineConfig } from 'vite';
import { timingSafeEqual } from 'node:crypto';
import baseConfig from './vite.config';

// Vite 6 rejects requests whose Host header it does not recognise, which would
// make every request through *.proxy.runpod.net fail with "Blocked request".
const RUNPOD_HOSTS = ['.proxy.runpod.net'];

// The upstream app assumes it is on localhost and has no real auth, so this
// gates the whole dev server — including the /api and /audio routes it proxies
// through to the Express backend on 3001.
function basicAuth(user: string, pass: string) {
  const expected = Buffer.from('Basic ' + Buffer.from(`${user}:${pass}`).toString('base64'));
  return {
    name: 'runpod-basic-auth',
    configureServer(server: any) {
      server.middlewares.use((req: any, res: any, next: any) => {
        const got = Buffer.from(req.headers.authorization || '');
        if (got.length === expected.length && timingSafeEqual(got, expected)) return next();
        res.statusCode = 401;
        res.setHeader('WWW-Authenticate', 'Basic realm="ace-step-ui"');
        res.end('Unauthorized');
      });
    },
  };
}

export default defineConfig(async (env) => {
  const base: any = typeof baseConfig === 'function' ? await (baseConfig as any)(env) : baseConfig;
  const user = process.env.UI_USER;
  const pass = process.env.UI_PASS;
  if (!user || !pass) throw new Error('UI_USER and UI_PASS must be set');
  return {
    ...base,
    server: {
      ...(base.server || {}),
      host: '0.0.0.0',
      port: Number(process.env.UI_PORT || 3000),
      allowedHosts: RUNPOD_HOSTS,
    },
    // Dependency source maps are useless here and the network volume has been
    // observed truncating some of the thousands of tiny .map files npm writes.
    // esbuild treats a truncated map as a fatal "Unexpected end of file in
    // source map"; not reading them at all sidesteps the whole class of failure.
    optimizeDeps: {
      ...(base.optimizeDeps || {}),
      esbuildOptions: { ...((base.optimizeDeps || {}).esbuildOptions || {}), sourcemap: false },
    },
    plugins: [...(base.plugins || []), basicAuth(user, pass)],
  };
});
VITECONFIG

# Zero-byte files are a reliable sign npm's writes did not all land. Source maps
# are already ignored, but truncated JS would fail in less obvious ways.
empty_js=$(find "$UI_DIR/node_modules" "$UI_DIR/server/node_modules" \
    -name "*.js" -size 0 2>/dev/null | wc -l)
if [[ "$empty_js" -gt 0 ]]; then
    echo
    echo "WARNING: $empty_js zero-byte .js files under node_modules — the install"
    echo "  was likely truncated. Re-run with: FORCE_REINSTALL=1 ./setup-ui.sh"
fi

echo
echo "[setup-ui] done. Now run: ./start-ui.sh"
